// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKFERdDHMpllLC0Ko1KIhMkMXCC6cWGlw',
    appId: '1:930031122918:web:eb3384b269b66fdf47fe27',
    messagingSenderId: '930031122918',
    projectId: 'creativeweb-2c424',
    authDomain: 'creativeweb-2c424.firebaseapp.com',
    storageBucket: 'creativeweb-2c424.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH8tTTriSjByC2OedduJwavA4plw2yVEE',
    appId: '1:930031122918:android:73b517f9608e9c4647fe27',
    messagingSenderId: '930031122918',
    projectId: 'creativeweb-2c424',
    storageBucket: 'creativeweb-2c424.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANzP0JyXRDk3NpTxtEuHt_OTYFfZsh9vw',
    appId: '1:930031122918:ios:ff5f09d519234eb447fe27',
    messagingSenderId: '930031122918',
    projectId: 'creativeweb-2c424',
    storageBucket: 'creativeweb-2c424.firebasestorage.app',
    iosBundleId: 'com.example.creativeweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANzP0JyXRDk3NpTxtEuHt_OTYFfZsh9vw',
    appId: '1:930031122918:ios:ff5f09d519234eb447fe27',
    messagingSenderId: '930031122918',
    projectId: 'creativeweb-2c424',
    storageBucket: 'creativeweb-2c424.firebasestorage.app',
    iosBundleId: 'com.example.creativeweb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKFERdDHMpllLC0Ko1KIhMkMXCC6cWGlw',
    appId: '1:930031122918:web:46a88968ecb32dd547fe27',
    messagingSenderId: '930031122918',
    projectId: 'creativeweb-2c424',
    authDomain: 'creativeweb-2c424.firebaseapp.com',
    storageBucket: 'creativeweb-2c424.firebasestorage.app',
  );
}
